// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/craigfurman/ezxfer/client"
)

type FakeProgressBarFactory struct {
	NewStub        func(fileSize int64) client.ProgressBar
	newMutex       sync.RWMutex
	newArgsForCall []struct {
		fileSize int64
	}
	newReturns struct {
		result1 client.ProgressBar
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeProgressBarFactory) New(fileSize int64) client.ProgressBar {
	fake.newMutex.Lock()
	fake.newArgsForCall = append(fake.newArgsForCall, struct {
		fileSize int64
	}{fileSize})
	fake.recordInvocation("New", []interface{}{fileSize})
	fake.newMutex.Unlock()
	if fake.NewStub != nil {
		return fake.NewStub(fileSize)
	} else {
		return fake.newReturns.result1
	}
}

func (fake *FakeProgressBarFactory) NewCallCount() int {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return len(fake.newArgsForCall)
}

func (fake *FakeProgressBarFactory) NewArgsForCall(i int) int64 {
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return fake.newArgsForCall[i].fileSize
}

func (fake *FakeProgressBarFactory) NewReturns(result1 client.ProgressBar) {
	fake.NewStub = nil
	fake.newReturns = struct {
		result1 client.ProgressBar
	}{result1}
}

func (fake *FakeProgressBarFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.newMutex.RLock()
	defer fake.newMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeProgressBarFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ client.ProgressBarFactory = new(FakeProgressBarFactory)
